#!/usr/bin/env bash
# script that sets up linux net firewall to block all incoming traffic EXCEPT TCP 22, 443, 80 to only allow 22/443/80
sudo apt install ufw
sudo ufw allow ssh
sudo ufw allow 'Nginx Full' (or sudo ufw allow 80/tcp && sudo ufw allow 443/tcp)
sudo ufw enable
